More configure macros

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -651,19 +651,14 @@ GIO_CFLAGS
 GLIB2_14_DEFINES
 GLIB2_14_LIBS
 GLIB2_14_CFLAGS
-GTK2_22_DEFINES
 GTK2_22_LIBS
 GTK2_22_CFLAGS
-GTK2_20_DEFINES
 GTK2_20_LIBS
 GTK2_20_CFLAGS
-GTK2_18_DEFINES
 GTK2_18_LIBS
 GTK2_18_CFLAGS
-GTK2_14_DEFINES
 GTK2_14_LIBS
 GTK2_14_CFLAGS
-GTK2_12_DEFINES
 GTK2_12_LIBS
 GTK2_12_CFLAGS
 GLIB_LIBS
@@ -672,6 +667,12 @@ GLIB2_26_DEFINES
 USE_GSETTINGS
 GLIB2_26_LIBS
 GLIB2_26_CFLAGS
+GTK2_24_DEFINES
+GTK2_22_DEFINES
+GTK2_20_DEFINES
+GTK2_18_DEFINES
+GTK2_14_DEFINES
+GTK2_12_DEFINES
 GTK_LIBS
 GTK_CFLAGS
 X11_LIBS
@@ -7560,16 +7561,25 @@ $as_echo "#define GTK3_ENABLED 1" >>confdefs.h
 $as_echo "#define GTK2_12_ENABLED 1" >>confdefs.h
 
 
+
 $as_echo "#define GTK2_14_ENABLED 1" >>confdefs.h
+
 
 
 $as_echo "#define GTK2_18_ENABLED 1" >>confdefs.h
 
 
+
 $as_echo "#define GTK2_20_ENABLED 1" >>confdefs.h
 
 
+
 $as_echo "#define GTK2_22_ENABLED 1" >>confdefs.h
+
+
+
+$as_echo "#define GTK2_24_ENABLED 1" >>confdefs.h
+
 
 
 
@@ -8224,6 +8234,81 @@ else
 $as_echo "yes" >&6; }
 	GTK2_22_DEFINES="-DGTK2_22_ENABLED -DGTK_DISABLE_DEPRECATED"
 $as_echo "#define GTK2_22_ENABLED 1" >>confdefs.h
+
+fi
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTK2_22" >&5
+$as_echo_n "checking for GTK2_22... " >&6; }
+
+if test -n "$GTK2_22_CFLAGS"; then
+    pkg_cv_GTK2_22_CFLAGS="$GTK2_22_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.24.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.24.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK2_22_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.24.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTK2_22_LIBS"; then
+    pkg_cv_GTK2_22_LIBS="$GTK2_22_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.24.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.24.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK2_22_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.24.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTK2_22_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.24.0" 2>&1`
+        else
+	        GTK2_22_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.24.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTK2_22_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Disabling Depreciated GTK Functions" >&5
+$as_echo "$as_me: Disabling Depreciated GTK Functions" >&6;}
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Disabling Depreciated GTK Functions" >&5
+$as_echo "$as_me: Disabling Depreciated GTK Functions" >&6;}
+else
+	GTK2_22_CFLAGS=$pkg_cv_GTK2_22_CFLAGS
+	GTK2_22_LIBS=$pkg_cv_GTK2_22_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	GTK2_22_DEFINES="-DGTK2_24_ENABLED -DGTK_DISABLE_DEPRECATED"
+$as_echo "#define GTK2_24_ENABLED 1" >>confdefs.h
 
 fi
 
