Fix GTK 2.14 specific code

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -676,6 +676,9 @@ GIO_CFLAGS
 GLIB2_14_DEFINES
 GLIB2_14_LIBS
 GLIB2_14_CFLAGS
+GTK2_14_DEFINES
+GTK2_14_LIBS
+GTK2_14_CFLAGS
 GTK2_12_DEFINES
 GTK2_12_LIBS
 GTK2_12_CFLAGS
@@ -828,6 +831,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 GTK2_12_CFLAGS
 GTK2_12_LIBS
+GTK2_14_CFLAGS
+GTK2_14_LIBS
 GLIB2_14_CFLAGS
 GLIB2_14_LIBS
 GIO_CFLAGS
@@ -1518,6 +1523,10 @@ Some influential environment variables:
               C compiler flags for GTK2_12, overriding pkg-config
   GTK2_12_LIBS
               linker flags for GTK2_12, overriding pkg-config
+  GTK2_14_CFLAGS
+              C compiler flags for GTK2_14, overriding pkg-config
+  GTK2_14_LIBS
+              linker flags for GTK2_14, overriding pkg-config
   GLIB2_14_CFLAGS
               C compiler flags for GLIB2_14, overriding pkg-config
   GLIB2_14_LIBS
@@ -8958,6 +8967,81 @@ $as_echo "yes" >&6; }
 	GTK2_12_DEFINES="-DGTK2_12_ENABLED"
 cat >>confdefs.h <<\_ACEOF
 #define GTK2_12_ENABLED 1
+_ACEOF
+
+fi
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for GTK2_14" >&5
+$as_echo_n "checking for GTK2_14... " >&6; }
+
+if test -n "$GTK2_14_CFLAGS"; then
+    pkg_cv_GTK2_14_CFLAGS="$GTK2_14_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.14.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.14.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTK2_14_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.14.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTK2_14_LIBS"; then
+    pkg_cv_GTK2_14_LIBS="$GTK2_14_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.14.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.14.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTK2_14_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.14.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTK2_14_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.14.0" 2>&1`
+        else
+	        GTK2_14_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.14.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTK2_14_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+                { $as_echo "$as_me:$LINENO: gtk_show_uti disabled" >&5
+$as_echo "$as_me: gtk_show_uti disabled" >&6;}
+elif test $pkg_failed = untried; then
+	{ $as_echo "$as_me:$LINENO: gtk_show_uti disabled" >&5
+$as_echo "$as_me: gtk_show_uti disabled" >&6;}
+else
+	GTK2_14_CFLAGS=$pkg_cv_GTK2_14_CFLAGS
+	GTK2_14_LIBS=$pkg_cv_GTK2_14_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	GTK2_14_DEFINES="-DGTK2_14_ENABLED"
+cat >>confdefs.h <<\_ACEOF
+#define GTK2_14_ENABLED 1
 _ACEOF
 
 fi
