Run make indent on source 	Enable compile with --enable-gseal (GTK3 prep)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -636,6 +636,12 @@ GIO_CFLAGS
 GLIB2_14_DEFINES
 GLIB2_14_LIBS
 GLIB2_14_CFLAGS
+GTK2_22_DEFINES
+GTK2_22_LIBS
+GTK2_22_CFLAGS
+GTK2_20_DEFINES
+GTK2_20_LIBS
+GTK2_20_CFLAGS
 GTK2_18_DEFINES
 GTK2_18_LIBS
 GTK2_18_CFLAGS
@@ -810,6 +816,10 @@ GTK2_14_CFLAGS
 GTK2_14_LIBS
 GTK2_18_CFLAGS
 GTK2_18_LIBS
+GTK2_20_CFLAGS
+GTK2_20_LIBS
+GTK2_22_CFLAGS
+GTK2_22_LIBS
 GLIB2_14_CFLAGS
 GLIB2_14_LIBS
 GIO_CFLAGS
@@ -1511,6 +1521,14 @@ Some influential environment variables:
               C compiler flags for GTK2_18, overriding pkg-config
   GTK2_18_LIBS
               linker flags for GTK2_18, overriding pkg-config
+  GTK2_20_CFLAGS
+              C compiler flags for GTK2_20, overriding pkg-config
+  GTK2_20_LIBS
+              linker flags for GTK2_20, overriding pkg-config
+  GTK2_22_CFLAGS
+              C compiler flags for GTK2_22, overriding pkg-config
+  GTK2_22_LIBS
+              linker flags for GTK2_22, overriding pkg-config
   GLIB2_14_CFLAGS
               C compiler flags for GLIB2_14, overriding pkg-config
   GLIB2_14_LIBS
@@ -7730,6 +7748,156 @@ else
 $as_echo "yes" >&6; }
 	GTK2_18_DEFINES="-DGTK2_18_ENABLED -DGTK_DISABLE_DEPRECATED"
 $as_echo "#define GTK2_18_ENABLED 1" >>confdefs.h
+
+fi
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTK2_20" >&5
+$as_echo_n "checking for GTK2_20... " >&6; }
+
+if test -n "$GTK2_20_CFLAGS"; then
+    pkg_cv_GTK2_20_CFLAGS="$GTK2_20_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.20.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.20.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK2_20_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.20.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTK2_20_LIBS"; then
+    pkg_cv_GTK2_20_LIBS="$GTK2_20_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.20.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.20.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK2_20_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.20.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTK2_20_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.20.0" 2>&1`
+        else
+	        GTK2_20_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.20.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTK2_20_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Disabling Depreciated GTK Functions" >&5
+$as_echo "$as_me: Disabling Depreciated GTK Functions" >&6;}
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Disabling Depreciated GTK Functions" >&5
+$as_echo "$as_me: Disabling Depreciated GTK Functions" >&6;}
+else
+	GTK2_20_CFLAGS=$pkg_cv_GTK2_20_CFLAGS
+	GTK2_20_LIBS=$pkg_cv_GTK2_20_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	GTK2_20_DEFINES="-DGTK2_20_ENABLED -DGTK_DISABLE_DEPRECATED"
+$as_echo "#define GTK2_20_ENABLED 1" >>confdefs.h
+
+fi
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTK2_22" >&5
+$as_echo_n "checking for GTK2_22... " >&6; }
+
+if test -n "$GTK2_22_CFLAGS"; then
+    pkg_cv_GTK2_22_CFLAGS="$GTK2_22_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.22.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.22.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK2_22_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.22.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTK2_22_LIBS"; then
+    pkg_cv_GTK2_22_LIBS="$GTK2_22_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.22.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.22.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK2_22_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.22.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTK2_22_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.22.0" 2>&1`
+        else
+	        GTK2_22_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.22.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTK2_22_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Disabling Depreciated GTK Functions" >&5
+$as_echo "$as_me: Disabling Depreciated GTK Functions" >&6;}
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Disabling Depreciated GTK Functions" >&5
+$as_echo "$as_me: Disabling Depreciated GTK Functions" >&6;}
+else
+	GTK2_22_CFLAGS=$pkg_cv_GTK2_22_CFLAGS
+	GTK2_22_LIBS=$pkg_cv_GTK2_22_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	GTK2_22_DEFINES="-DGTK2_22_ENABLED -DGTK_DISABLE_DEPRECATED"
+$as_echo "#define GTK2_22_ENABLED 1" >>confdefs.h
 
 fi
 
